#docker-compose for developpement
version: '2'

services:

  gwts-api:
    build: .
    container_name: gwts-api-server-dev
    command: nodemon -L --debug=5858 bin/www
    image: gwts-api-server
    volumes:
        - "./app:/app"
    ports:
        - "3030:3030"
        - "5858:5858"
    links:
        - mongo

  mongo:
    container_name: gwts-mongo-dev
    image: mongo
    ports:
      - "27017:27017"
    # volumes_from :
    #   - mongodata

  # mongodata :
  #   images : tianon/true
  #   volumes : /data/db
  #   command : echo 'Data container for mongodb'

