#docker-compose for developpement
version: '2'

services:
  rivierra-api:
    build: .
    container_name: rivierra-api-server-dev
    command: nodemon -L --debug=5858 src/server
    image: gwts-api-server
    volumes:
        - "./src:/src"
    ports:
        - "3030:3030"
        - "5858:5858"
    links:
        - mongo
  mongo:
    container_name: mongo-dev
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/user_adm/Documents/docker/mongodb:/data/db
  